### ISSUE TITLE
Nekompatibilní závislosti

### ISSUE THREAD

**Issue by encukou** [pyvec/jechova#17]
Dobrý den, paní Jechová.

Nový `pip` je nějakej cytrej a při instalaci nadává, že verze uvedené v `requirements.txt` nejsou vzájemně kompatibilní:

```
ERROR: Cannot install -r /home/pviktori/dev/jechova/requirements.txt (line 2) and arrow==0.17.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested arrow==0.17.0
    ics 0.7 depends on arrow<0.15 and >=0.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by honzajavorek** [comment]
To je ten nový resolver? Jaká verze pipu?

**Comment by honzajavorek** [comment]
Hmm, je možné, že dependabot něco upgradne, ale nezjistí, jestli ty věci fungují společně? 🤔 Tak to asi mohlo vzniknout. Dependabot mergne dependency na základě procházejících testů, ale v https://github.com/pyvec/jechova/blob/master/.github/workflows/build.yml se závislosti paní Jechové ani neinstalují.

**Comment by encukou** [comment]
Jo, to asimůže být ono.

**Comment by encukou** [comment]
Ano, nový resolver v `20.3b1`.
```
$ python -m pip --version
pip 20.3b1 from /home/pviktori/dev/jechova/__venv__/lib64/python3.8/site-packages/pip (python 3.8)
```

**Comment by honzajavorek** [comment]
Tak pip 20.2.4 mi to nainstaluje v pohodě. Přidám ale aspoň "testy", ať se nestane to, co jsem napsal v komentáři výše. Co s tím nejnovějším pipem nevím. Chtělo by asi ověřit, zda to není bug v pipu?

```
$ pip --version
pip 20.2.4 from /Users/honza/Projects/jechova/venv/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by encukou** [comment]
Není, ics opravdu závisí na `arrow (<0.15,>=0.11)`.
Autoři pipu už nějakou dobu avizujou, že pip začne konečně brát ohled na všechny závislosti, ne jen ty z balíčku který právě instaluje.

**Comment by honzajavorek** [comment]
Koukám, že to už někdo přede mnou někde řešil, tipuju python.cz... https://github.com/C4ptainCrunch/ics.py/issues/169 & https://github.com/C4ptainCrunch/ics.py/issues/239#issuecomment-599068294

**Comment by honzajavorek** [comment]
Podle všeho by ics v8 nemělo už ani záviset na arrow. Hm. Ale ještě není vydaný.

**Comment by honzajavorek** [comment]
Tak už asi máme nový pip v GitHub Actions a poslední dva buildy kvůli přesně tomuto spadly na instalaci 😬
